const APP_NAME = "@CATCH_LEADS";

export const QUERY_KEYS = {
	SETTINGS: [`${APP_NAME}:SETTINGS`],
	PROFILE: [`${APP_NAME}:PROFILE`],
	GROWTH_TOTAL_LEADS: [`${APP_NAME}:GROWTH_TOTAL_LEADS`],
	ALL_CAMPAIGNS: [`${APP_NAME}:ALL_CAMPAIGNS`],
	ALL_LEADS: [`${APP_NAME}:ALL_LEADS`],
};
