
service: ProjectName
useDotenv: true
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  
package:
  individually: true
  excludeDevDependencies: true
  
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentMethod: direct
  architecture: arm64
  accessKeyId: ${env:AWS_ACCESS_KEY_ID}
  secretAccessKeyId: ${env:AWS_SECRET_ACCESS_KEY}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:ConditionCheckItem
            - dynamodb:BatchWriteItem
          Resource: 
            - !GetAtt ProjectNameTable.Arn
            - !Sub ${ProjectNameTable.Arn}/index/GSI1Index
  environment:
    STAGE: ${self:provider.stage}
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - '*'
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
          
resources:
  Resources:
    ProjectNameTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ProjectNameTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1Index
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        
custom:
  stages:
    - dev
    - prod
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - '@aws-sdk/*'
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10 
    
functions:
  signinWithGoogle:
    handler: src/server/functions/auth/signin-with-google.handler
    events:
      - httpApi:
          method: POST
          path: /auth/google
  getProfile:
    handler: src/server/functions/auth/profile.handler
    events:
      - httpApi:
          method: GET
          path: /auth/profile
  getGrowthTotalLeads:
    handler: src/server/functions/lead/get-growth-total.handler
    events:
      - httpApi:
          method: GET
          path: /lead/growth-total
  createLead:
    handler: src/server/functions/lead/create.handler
    events:
      - httpApi:
          method: POST
          path: /lead/create
  getAllLeads:
    handler: src/server/functions/lead/get-all.handler
    events:
      - httpApi:
          method: GET
          path: /lead/all
  getAllCampaigns:
    handler: src/server/functions/campaign/get-all.handler
    events:
      - httpApi:
          method: GET
          path: /campaign/all
  createCampaign:
    handler: src/server/functions/campaign/create.handler
    events:
      - httpApi:
          method: POST
          path: /campaign/create
        
  